# Generated by Django 5.0 on 2023-12-31 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 31, 17, 11, 53, 272751, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
