# Generated by Django 5.0 on 2023-12-31 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_customer_date_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='invoice.invoice'),
        ),
    ]
